apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "gluster-volume"
spec:
  capacity:
    storage: "20Gi"
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: "storage"
  accessModes:
    - "ReadWriteOnce"
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "vol01"
    readOnly: false
